/*
 * Copyright (c) 1995,1996
 * David M. Howard
 * daveh@hendrix.reno.nv.us
 * www.greatbasin.net/~daveh
 *
 * Permission to use, copy, modify, distribute and sell this software
 * and its documentation for any purpose is hereby granted without fee,
 * provided that the above copyright notice appear in all copies and
 * that both that copyright notice and this permission notice appear
 * in supporting documentation.  
 * David M. Howard makes no representations about the suitability of this
 * software for any purpose.  It is provided 'as is' without express or
 * implied warranty. Do not use it in systems where damage to property
 * or injury to people may occur in the event of a malfunction
 *
 * A supported version of this software including updates is available.
 * Consulting services for porting, modification, web user interface design
 * and implementation are available also.
 * Contact David M. Howard at the above email address for details.
 */
/*H*/
#ifndef __SOCKETQ__
#define __SOCKETQ__

/* keep implementation local to file containing function bodies */
typedef void *SOCKET_QUEUE;

extern SOCKET_QUEUE socket_qinit(long size);
extern void         socket_qsend(SOCKET_QUEUE q,SOCKET s);
extern SOCKET       socket_qrecv(SOCKET_QUEUE q);

#endif
