rename ct.cls          ct.class         
rename ct.htm          ct.html          
rename ct.jav          ct.java          
rename example.cls     example.class    
rename example.htm     example.html     
rename example.jav     example.java     
rename readst.cls      readstream.class 
rename stream.cls   streaming.class  
rename stream.htm   streaming.html   
rename stream.jav   streaming.java   

