rename          ct.class         ct.cls 
rename          ct.html          ct.htm 
rename          ct.java          ct.jav 
rename     example.class    example.cls 
rename     example.html     example.htm 
rename     example.java     example.jav 
rename      readstream.class readst.cls 
rename   streaming.class  stream.cls 
rename   streaming.html   stream.htm 
rename   streaming.java   stream.jav 

